export default  {
    products: [{
        name: 'shirt1',
        _id: '1',
        category: 'shirt1',
        image: '/images/d1.jpg',
        price: 50,
        brand: 'Nike',
        rating: '4.5 ',
        numReviews: '10',
        countInStock: 3,
    },{
        name: 'shit2',
        _id: '2',
        image: '/images/d1.jpg',
        category: 'shirt',
        price: 50,
        brand: 'Nike',
        rating: '4.5 ',
        numReviews: '10',
        countInStock: 2,
    },{
        name: 'shit3',
        _id: '3',
        category: 'shirt',
        image: '/images/d1.jpg',
        price: 50,
        brand: 'Nike',
        rating: '4.5 ',
        numReviews: '10',
        countInStock: 3,
        
    },{
        name: 'shirt4',
        _id: '4',
        category: 'shirt',
        image: '/images/d1.jpg',
        price: 50,
        brand: 'Nike',
        rating: '4.5 ',
        numReviews: '10',
        countInStock: 4,
    },{
        name: 'shit5',
        _id: '5',
        category: 'pant',
        image: '/images/d1.jpg',
        price: 50,
        brand: 'Nike',
        rating: '4.5 ',
        numReviews: '10',
        countInStock: 4,
    },
    
]
}